# Generated by Django 4.2 on 2023-05-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gststock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_vente', models.DateField(auto_now_add=True)),
                ('heure_vente', models.TimeField(auto_now_add=True)),
                ('prix_rendu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gststock.medicament')),
            ],
        ),
    ]
