# Generated by Django 4.2 on 2023-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('adress', models.TextField()),
                ('qualite', models.CharField(default='parfite', max_length=100)),
            ],
        ),
    ]
