# Generated by Django 4.2 on 2023-05-24 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gststock', '0001_initial'),
        ('client', '0002_alter_patients_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(default=datetime.date.today)),
                ('imprimee', models.BooleanField(default=False)),
                ('annulee', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.patients')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentsFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factures.facture')),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gststock.medicament')),
            ],
        ),
    ]
