# Generated by Django 4.2 on 2023-05-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeBarre', models.DecimalField(decimal_places=5, max_digits=20)),
                ('designation', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=100)),
                ('forme', models.CharField(blank=True, max_length=50, null=True)),
                ('DCI', models.CharField(blank=True, max_length=50, null=True)),
                ('qte', models.IntegerField(blank=True, null=True)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('stock_min', models.IntegerField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('date_permeotion', models.DateField()),
                ('lieu_med', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
