# Generated by Django 4.2 on 2023-05-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gststock', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
