# Generated by Django 4.2 on 2023-05-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gfournisseur', '0001_initial'),
        ('gststock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField()),
                ('date_commande', models.DateField()),
                ('imprimee', models.BooleanField(default=False)),
                ('annulee', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gfournisseur.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('description', models.TextField()),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcommande.commande')),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gststock.medicament')),
            ],
        ),
    ]
