# Generated by Django 4.2 on 2023-05-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gststock', '0001_initial'),
        ('gfournisseur', '0001_initial'),
        ('gcommande', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commande',
            new_name='Commandes',
        ),
        migrations.RenameModel(
            old_name='MedicamentCommande',
            new_name='MedicamentCommandes',
        ),
    ]
