# Generated by Django 4.2 on 2023-05-21 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfournisseur', '0001_initial'),
        ('gststock', '0001_initial'),
        ('gcommande', '0002_rename_commande_commandes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gcommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField()),
                ('date_commande', models.DateField(default=datetime.date.today)),
                ('imprimee', models.BooleanField(default=False)),
                ('annulee', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gfournisseur.fournisseur')),
            ],
        ),
        migrations.RenameModel(
            old_name='MedicamentCommandes',
            new_name='MedicamentsCommande',
        ),
        migrations.DeleteModel(
            name='Commandes',
        ),
        migrations.AlterField(
            model_name='medicamentscommande',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcommande.gcommandes'),
        ),
    ]
