# Generated by Django 4.2 on 2023-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcommande', '0003_gcommandes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentscommande',
            name='C',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicamentscommande',
            name='D',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicamentscommande',
            name='S',
            field=models.FloatField(default=0.0),
        ),
    ]
